# Generated by Django 6.0.6 on 2026-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/student')),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
